apiVersion: v1
kind: Service
metadata:
  name: jungle-service
spec:
  type: NodePort
  selector:
    app: jungle
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: jungle-deployment
  labels:
    app: jungle
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jungle
  template:
    metadata:
      labels:
        app: jungle
    spec:
      containers:
      - name: jungle
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        ports:
        - containerPort: 8080
